[package]
name = "Nested_Lists"
version = "0.1.0"
authors = ["mrmjt <jamshaid.tahiri1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.7"